backend:
  # opentelemetry-operator injects the OTel java agent (needs the
  # yas-instrumentation Instrumentation CR in the target namespace)
  podAnnotations:
    instrumentation.opentelemetry.io/inject-java: "true"
  image:
    repository: baohuyhuy/yas-customer
    tag: main

  nameOverride: customer
  fullnameOverride: customer
  databaseName: customer
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
  extraVolumes:
    - name: customer-application
      configMap:
        name: customer-application-configmap
  extraVolumeMounts:
    - name: customer-application
      mountPath: /opt/yas/customer
  extraApplicationConfigPaths:
    - /opt/yas/customer/customer-application.yaml
